# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reporting_system
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

# Server Config

server:
  port: 9002

